added plugin files
CoconutLizard/BlueprintSearchVSExtension pull request #1
Opened 2021-06-08 15:50 UTC by Davide-CL

2021-06-09 08:02 UTC, LizardThief requested changes

2021-06-09 08:02 UTC, LizardThief commented on Source/FindInBlueprintExternal/Classes/FiBCommandlet.h
> +
Indenting is a bit screwy here. Should all be only one tab.

2021-06-09 08:02 UTC, LizardThief commented on Source/FindInBlueprintExternal/Private/FiBCommandlet.cpp
> +//#include "SharedPointer.h"
Please write includes with paths relative to the Source folder - like "Developer/AssetTools/Public/AssetToolsModule.h", not "AssetRegistryModule.h".

Also remove the commented out SharedPointer.h include if you don't need it

2021-06-09 08:02 UTC, LizardThief commented on Source/FindInBlueprintExternal/Private/FiBCommandlet.cpp
> +		{
Inconsisted brace positioning - UE4 standard is `{` on its own line (like the if)

2021-06-09 08:02 UTC, LizardThief commented on Source/FindInBlueprintExternal/Private/FiBCommandlet.cpp
> +
You don't need a blank line between every line of code - try to group them logically

2021-06-09 08:02 UTC, LizardThief commented on Source/FindInBlueprintExternal/Private/FiBCommandlet.cpp
> +	UE_LOG(LogTemp, Warning, TEXT("Test text"));
Don't need this :)

You do need to log out OutItemsFound though maybe?

2021-06-09 08:02 UTC, LizardThief commented on Source/FindInBlueprintExternal/Private/FiBCommandlet.cpp
> +    return int32();
we'd normally just write
```suggestion
    return 0;
```

2021-06-09 08:02 UTC, LizardThief commented on Source/FindInBlueprintExternal/Private/FindInBlueprintExternal.cpp
> +IMPLEMENT_MODULE(FFindInBlueprintExternalModule, FindInBlueprintExternal)
There should be a newline at the end of the file. It helps with merging changes later

2021-06-09 08:02 UTC, LizardThief commented on Source/FindInBlueprintExternal/Private/FiBCommandlet.cpp
> +		while (!StreamSearch.IsComplete()) FFindInBlueprintSearchManager::Get().Tick(.0);
Use braces around the loop body and separate into multiple lines please

2021-06-09 09:15 UTC, Josef-Rare commented on Source/FindInBlueprintExternal/Private/FiBCommandlet.cpp
> +//#include "SharedPointer.h"
Tooling general coding standards and examples are here https://coconutlizard.atlassian.net/wiki/spaces/CLKB/pages/823132168/MemFerret+Coding+Standards

2021-06-09 09:17 UTC, Josef-Rare commented on Source/FindInBlueprintExternal/Classes/FiBCommandlet.h
> +class UFiBCommandlet : public UCommandlet
General good practice to mark the class final if possible

2021-06-09 09:18 UTC, Josef-Rare commented on Source/FindInBlueprintExternal/FindInBlueprintExternal.Build.cs
> +		PrivateDependencyModuleNames.AddRange(
Delete all the empty template AddRange calls and the 'add here' comments

2021-06-09 09:22 UTC, Josef-Rare commented on Source/FindInBlueprintExternal/Private/FiBCommandlet.cpp
> +	FAssetRegistryModule* AssetRegistryModule = &FModuleManager::LoadModuleChecked<FAssetRegistryModule>(TEXT("AssetRegistry"));
We get a reference back from this ftn so just assign to a reference
```suggestion
	FAssetRegistryModule& AssetRegistryModule = FModuleManager::LoadModuleChecked<FAssetRegistryModule>(TEXT("AssetRegistry"));
```

2021-06-09 09:24 UTC, Josef-Rare commented on Source/FindInBlueprintExternal/Private/FiBCommandlet.cpp
> +	FAssetRegistryModule* AssetRegistryModule = &FModuleManager::LoadModuleChecked<FAssetRegistryModule>(TEXT("AssetRegistry"));
Assigning to a pointer we lose the inherent safety of a reference, and there's no need for that here.

2021-06-10 14:21 UTC, willhinds requested changes

2021-06-10 14:21 UTC, willhinds commented on FindInBlueprintExternal.uplugin
> +}
Newline at the end of this file

2021-06-10 14:21 UTC, willhinds commented on Source/FindInBlueprintExternal/Classes/FiBCommandlet.h
> +#pragma once
Do we have a Coconut Lizard Copyright notice for our Tool plugins, or do we use Epic's @Josef-CL ?

2021-06-10 14:21 UTC, willhinds commented on Source/FindInBlueprintExternal/FindInBlueprintExternal.Build.cs
> +				"Kismet"
I think it's good to put these in alphabetical order - makes it easier to see what's there and what's not at a glance. If you haven't got it already Ori's LizardVS extension has an Alphabetiser

2021-06-10 14:21 UTC, willhinds commented on Source/FindInBlueprintExternal/Private/FindInBlueprintExternal.cpp
> +	// This code will execute after your module is loaded into memory; the exact timing is specified in the .uplugin file per-module
You can remove these comments. And probably remove both of these functions as well, unless they're pure virtual in the base class?

2021-06-10 16:15 UTC, cl-sambendell commented on Source/FindInBlueprintExternal/Classes/FiBCommandlet.h
> +#pragma once
Yeah we use `// Copyright (C) Coconut Lizard Limited. All rights reserved.`

2021-06-11 08:47 UTC, LizardThief requested changes

2021-06-11 08:47 UTC, LizardThief commented on Source/FindInBlueprintExternal/FindInBlueprintExternal.Build.cs
> +			);
Indenting is very broken here - mixed tab and space indenting does not work, as different people/software have different tab sizes.

2021-06-11 09:37 UTC, Josef-Rare commented on Source/FindInBlueprintExternal/FindInBlueprintExternal.Build.cs
> +			);
We should get an editorconfig into this repo to help with indentations etc

2021-06-14 10:14 UTC, LizardThief requested changes

2021-06-14 10:14 UTC, LizardThief commented on Source/FindInBlueprintExternal/Private/FiBCommandlet.cpp
> +#include "FiBResultsToJsonWriter.h"
You should only have one of these two - probably the first one by the include style?

2021-06-14 12:19 UTC, LizardThief approved these changes

2021-06-15 10:21 UTC, willhinds approved these changes

2021-06-16 10:26 UTC, merged