Added case to handle missing file
CoconutLizard/BlueprintSearchVSExtension pull request #10
Opened 2021-09-07 13:37 UTC by Davide-CL

2021-09-07 13:40 UTC, Ethan-CL approved these changes

2021-09-08 08:32 UTC, Ori-CL requested changes
Make the changes to the `MakeSearch` function that we discussed on teams.

2021-09-08 08:32 UTC, Ori-CL commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHandlers/ExecuteSearchHandler.cs
> +				PathFinderHelper.FindPaths();
Migrate this so that you call the expected procedure if this results in the paths being found.

2021-09-08 09:08 UTC, Ori-CL approved these changes
LGTM!

2021-09-08 09:10 UTC, merged