Feature/subtask write results to json
CoconutLizard/BlueprintSearchVSExtension pull request #2
Opened 2021-06-17 14:42 UTC by Davide-CL

2021-06-17 14:50 UTC, willhinds commented on Source/FindInBlueprintExternal/Private/FiBResultsToJsonWriter.cpp
> +
Remove this whitespace

2021-06-17 14:55 UTC, willhinds requested changes

2021-06-17 14:55 UTC, willhinds commented on Source/FindInBlueprintExternal/Private/FiBResultsToJsonWriter.cpp
> +
Remove this whitespace

2021-06-17 14:55 UTC, willhinds commented on Source/FindInBlueprintExternal/Classes/FiBResultsToJsonWriter.h
> +	void WriteDataToJson(const TArray<FSearchResult>& Data, bool IsRoot = true);
Booleans should start with a lower case b, so this should be bIsRoot (unless the Tools coding standard is different?)

2021-06-17 14:55 UTC, willhinds commented on Source/FindInBlueprintExternal/Private/FiBCommandlet.cpp
> +#include "FindInBlueprintExternal/Classes/FiBResultsToJsonWriter.h"
Alphabetises these includes

2021-06-17 14:55 UTC, willhinds commented on Source/FindInBlueprintExternal/Private/FiBCommandlet.cpp
> +DEFINE_LOG_CATEGORY_STATIC(LogFiBCommandlet, Log, All);
You should include the LogMacros.h header to use this macro

2021-06-17 15:44 UTC, cl-sambendell commented on Source/FindInBlueprintExternal/Private/FiBResultsToJsonWriter.cpp
> +	}
It's really up to personal preference, though I find flipping this if statement often reads better and mandates your requirements better. In the current state this is saying "we have a problem if there are 0 or less items", which is partly always true, there's a serious issue if you have negative items in an array.
I like to read this as a requirement, so you ask if there are more than 0 items in the array, and then encapsulate your logic in it. As so:
```suggestion
	if (SearchResults.Num() > 0)
	{
		DoStuff();
	}
```

2021-06-17 15:48 UTC, cl-sambendell commented on Source/FindInBlueprintExternal/Private/FiBCommandlet.cpp
> +	FiBResultsToJsonWriter Writer(*FileArchive.Get());
TUniquePtr / TSharedPtr have overloaded dereference operators ( `*` and `->` ) that will return the object pointed to without needing to call `Get()` first
```suggestion
	FiBResultsToJsonWriter Writer(*FileArchive);
```

2021-06-17 15:55 UTC, cl-sambendell commented on Source/FindInBlueprintExternal/Classes/FiBResultsToJsonWriter.h
> +	void WriteDataToJson(const TArray<FSearchResult>& Data, bool IsRoot = true);
Nothing explicit about this in our tooling coding standard (put b infront from Unreal Coding Standard)

2021-06-17 15:57 UTC, cl-sambendell commented on Source/FindInBlueprintExternal/Private/FiBCommandlet.cpp
> +#include "FindInBlueprintExternal/Classes/FiBResultsToJsonWriter.h"
Header should go right at the top underneath the FiBCommandlet.h
https://coconutlizard.atlassian.net/wiki/spaces/CLKB/pages/823132168/Tools+Coding+Standards

2021-06-18 06:31 UTC, Ori-CL requested changes
### Good stuff dude, nice use of unreal libraries & coding standards in writing this :) 

### Notes
- A few whitespaces could be removed 
- I also added a comment regarding the recursive functions, wait for the responses from the team with regards to that comment before you change anything (it might be unnecessary and I'm just being silly :D).

2021-06-18 06:31 UTC, Ori-CL commented on Source/FindInBlueprintExternal/Private/FiBResultsToJsonWriter.cpp
> +	}
This comment has a downside of repeated code, so it may not be the path you choose to take, however, depending on how many recursive calls you end up having, this may be useful.

You could create two separate functions here, one for the root parsing and one for the children, that way you won't need to pass the **IsRoot** parameter for each child write call, furthermore it saves you from the branching (however, it could be that this gets optimized away, and thus this change doesn't matter, tagging @willhinds @cl-sambendell @LizardThief for visibility and opinions).

```cpp
void FiBResultsToJsonWriter::WriteRootDataToJson(const TArray<FSearchResult>& SearchResults)
{
    JsonWriter->WriteArrayStart();
    
    for (const FSearchResult& Item : SearchResults)
    {
        JsonWriter->WriteObjectStart();
        JsonWriter->WriteValue(TEXT("Value"), Item->GetDisplayString().ToString());
        WriteChildDataToJson(Item->Children);
        JsonWriter->WriteObjectEnd();
    }
    JsonWriter->WriteArrayEnd();
}

////////////////////////////////////////////////////////////////////////////////////////// 

void FiBResultsToJsonWriter::WriteChildDataToJson(const TArray<FSearchResult>& SearchResults)
{
    JsonWriter->WriteArrayStart("Children");    
    
    for (const FSearchResult& Item : SearchResults)
    {
        JsonWriter->WriteObjectStart();
        JsonWriter->WriteValue(TEXT("Value"), Item->GetDisplayString().ToString());
        WriteChildDataToJson(Item->Children);
        JsonWriter->WriteObjectEnd();
    }
    JsonWriter->WriteArrayEnd();
}
``

2021-06-18 06:31 UTC, Ori-CL commented on Source/FindInBlueprintExternal/Private/FiBResultsToJsonWriter.cpp
> +
Remove this whitespace

2021-06-18 06:31 UTC, Ori-CL commented on Source/FindInBlueprintExternal/Private/FiBResultsToJsonWriter.cpp
> +
Remove the extra whitespace here too

2021-06-18 12:00 UTC, Josef-Rare commented on Source/FindInBlueprintExternal/Classes/FiBResultsToJsonWriter.h
> +	void WriteDataToJson(const TArray<FSearchResult>& Data, bool IsRoot = true);
Rare differs there, we don't.

2021-06-18 12:00 UTC, Josef-Rare commented on Source/FindInBlueprintExternal/Private/FiBCommandlet.cpp
> +DEFINE_LOG_CATEGORY_STATIC(LogFiBCommandlet, Log, All);
That's in CoreMinimal though I think?

2021-06-18 13:07 UTC, cl-sambendell commented on Source/FindInBlueprintExternal/Private/FiBResultsToJsonWriter.cpp
> +	}
I think this could be rewritten in such a way that it only writes a singular FSearchResult instead of expecting a TArray. This way you can write the code as such:
```cpp
void FiBResultsToJsonWriter::WriteSearchResultToJson(const FSearchResult& SearchResult)
{
    JsonWriter->WriteObjectStart();
    JsonWriter->WriteValue(TEXT("Value"), Item->GetDisplayString().ToString());
    
    // Could even wrap this in an if to not write out the child array if it's empty
    // I'm not 100% on the requirements of JSON, does it always need to exist?
    JsonWriter->WriteArrayStart("Children");  
    for (const FSearchResult& Child : SearchResult->Children)
    {
        WriteSearchResultToJson(Item->Child);
    }
    JsonWriter->WriteArrayEnd();

    JsonWriter->WriteObjectEnd();
}

void FiBResultsToJsonWriter::WriteDataToJson(const TArray<FSearchResult>& SearchResults)
{
    // This may also want to go even earlier - depends what the JSON file is expecting with no search data found
    if (SearchResults.Num() > 0)
    {
        JsonWriter->WriteArrayStart();  
        for (const FSearchResult& Item : SearchResults)
        {
            WriteSearchResultToJson(Item);
        }
        JsonWriter->WriteArrayEnd();
    }
}
```

2021-06-18 13:08 UTC, cl-sambendell commented on Source/FindInBlueprintExternal/Private/FiBResultsToJsonWriter.cpp
> +	}
This combines the suggestion of removing the root variable without also having the code duplication

2021-06-18 14:17 UTC, Ori-CL commented on Source/FindInBlueprintExternal/Private/FiBResultsToJsonWriter.cpp
> +	}
Thanks for optimizing the solution Sam, to answer your question on line 7, NewtonSoft 's JSON library (C#) will handle both cases (children array present & not), so wrapping it in an if statement to stop the unnecessary writing is valid.

2021-06-21 11:02 UTC, willhinds requested changes

2021-06-21 11:02 UTC, willhinds commented on Source/FindInBlueprintExternal/Classes/FiBResultsToJsonWriter.h
> +#include <Editor/Kismet/Public/FindInBlueprintManager.h>
Add CoreMinimal.h as the first include please - sorry I missed this one on the last pass!

2021-06-21 11:02 UTC, willhinds commented on Source/FindInBlueprintExternal/Classes/FiBResultsToJsonWriter.h
> +#include <Editor/Kismet/Public/FindInBlueprintManager.h>
You don't actually _need_ CoreMinimal.h here, as you've successfully included everything you use, but it's the coding standard we've gone for. CoreMinimal.h has SharedPointer.h in it so you can remove that include if you wish.

2021-06-21 11:20 UTC, willhinds approved these changes

2021-06-21 12:15 UTC, merged