Added Extension Files
CoconutLizard/BlueprintSearchVSExtension pull request #3
Opened 2021-06-23 10:48 UTC by Davide-CL

2021-06-23 12:51 UTC, Ori-CL requested changes
Looks good, it would be good to get a few more comments in some files about what is going on, and also have left some comments regarding some copyright stuff needing to be moved around.

2021-06-23 12:51 UTC, Ori-CL commented on Source/BlueprintSearchVSExtension/Config/source.extension.vsixmanifest
> +    <Description>Empty VSIX Project.</Description>
A couple of things need updating in this manifest file:

- Publisher -> This should be "Coconut Lizard"
- Description -> A more contextual description for the extension would be useful to people using this.

If you open this file in visual studio, there should be an easy way of changing this data. 
![image](https://user-images.githubusercontent.com/63600713/123093137-34d12e00-d423-11eb-88be-ae5fa5ebe773.png)

2021-06-23 12:51 UTC, Ori-CL commented on Source/BlueprintSearchVSExtension/Source/BlueprintSearchVSPackage.cs
> +using Microsoft.VisualStudio.Shell;
Please add the copyright comment at the top of all source files, to match the assembly info file in this commit, add the following:

// Copyright (C) Coconut Lizard Limited. All rights reserved.

// ---------------------------------------------------------

2021-06-23 12:51 UTC, Ori-CL commented on Source/BlueprintSearchVSExtension/Source/BlueprintSearchVSPackage.cs
> +	// Copyright (C) Coconut Lizard Limited. All rights reserved.
Move the copyright to the top of the file please

2021-06-23 12:51 UTC, Ori-CL commented on Source/BlueprintSearchVSExtension/Source/UI/ToolWindows/BlueprintSearchWindow/BlueprintSearchVSWindowControl.xaml.cs
> +using BlueprintSearch.Commands.CommandHandlers;
Add copyright here

2021-06-23 12:51 UTC, Ori-CL commented on Source/BlueprintSearchVSExtension/Source/BlueprintSearchVSPackage.cs
> +	/// </remarks>
It'll probably be good to either remove this default comment or update it to match this extension's functionality.

2021-06-23 15:03 UTC, willhinds requested changes
What are the two .png files for?

Looks good! I'm not well versed in C# so Ori is definitely the main reviewer here. Just one issue I saw with the paths for the editor binary and the .uproject file in the shell script. This might not be a straight forward fix. We can have a chat and see but it might that we make a task to sort this out rather than do it here.

2021-06-23 15:03 UTC, willhinds commented on Source/BlueprintSearchVSExtension/BlueprintSearchVS.csproj
> +<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
Is this a new file? Should we pop the copyright logo here if so?

2021-06-23 15:03 UTC, willhinds commented on Source/BlueprintSearchVSExtension/Source/Scripts/RunSearchCommandlet.sh
> +"D:/UnrealEngine4.26/Engine/Binaries/Win64/UE4Editor-Cmd.exe" D:/UnrealEngine4.26/Projects/VehicleGame/VehicleGame.uproject -run=FiB $1
I think that this won't work on someone else's computer where their engine path is different. We need to find a way to find the UE4Editor-Cmd.exe path. I'm sure there will be a way of doing this but I'm not sure.

2021-06-23 15:03 UTC, willhinds commented on Source/BlueprintSearchVSExtension/Source/Scripts/RunSearchCommandlet.sh
> +"D:/UnrealEngine4.26/Engine/Binaries/Win64/UE4Editor-Cmd.exe" D:/UnrealEngine4.26/Projects/VehicleGame/VehicleGame.uproject -run=FiB $1
Also the same is true of the VehicleGame.uproject. It would be good to try and use the currently active/ open .uproject. This might be a bit trickier to do - and might be a new separate task.

2021-06-23 15:03 UTC, willhinds commented on Source/BlueprintSearchVSExtension/Source/Scripts/RunSearchCommandlet.sh
> +"D:/UnrealEngine4.26/Engine/Binaries/Win64/UE4Editor-Cmd.exe" D:/UnrealEngine4.26/Projects/VehicleGame/VehicleGame.uproject -run=FiB $1
@Ori-CL Wondering if your VSExtension travels have brought you across anything that would help with either of these?

2021-06-24 09:17 UTC, Josef-Rare commented on Source/BlueprintSearchVSExtension/Source/Scripts/RunSearchCommandlet.sh
> +"D:/UnrealEngine4.26/Engine/Binaries/Win64/UE4Editor-Cmd.exe" D:/UnrealEngine4.26/Projects/VehicleGame/VehicleGame.uproject -run=FiB $1
Yeah Will's right. Unless there's a vary quick fix though it might be best doing this as a separate task immediately after in order to not bloat this review?

2021-06-24 14:42 UTC, Ori-CL commented on Source/BlueprintSearchVSExtension/Source/Scripts/RunSearchCommandlet.sh
> +"D:/UnrealEngine4.26/Engine/Binaries/Win64/UE4Editor-Cmd.exe" D:/UnrealEngine4.26/Projects/VehicleGame/VehicleGame.uproject -run=FiB $1
These comments are valid and a separate task should be created to resolve the way in which we currently call this process, it is doable directly from C#, and LizardVS already extracts the .uproject path of an unreal solution, as well as the paths of executables such as this one. 

I have shown david where it is, he will work on migrating it over in a separate task.

2021-06-24 15:51 UTC, willhinds commented on Source/BlueprintSearchVSExtension/Source/Scripts/RunSearchCommandlet.sh
> +"D:/UnrealEngine4.26/Engine/Binaries/Win64/UE4Editor-Cmd.exe" D:/UnrealEngine4.26/Projects/VehicleGame/VehicleGame.uproject -run=FiB $1
Yep we'll add a task to solve this next. We'll probably use both Ori's .uproject finding code and Josef's suggestion to incorporate Search Everything API

2021-06-24 15:51 UTC, willhinds approved these changes

2021-06-25 09:13 UTC, merged