Feature/blueprint search vs extension sub tasks/find path for uproject and ue4 editor
CoconutLizard/BlueprintSearchVSExtension pull request #4
Opened 2021-06-29 13:46 UTC by Davide-CL

2021-06-29 13:57 UTC, Ethan-CL reviewed
Mostly looks good as far as I can see - just a couple of whitespace changes which should be left as they were

2021-06-29 13:57 UTC, Ethan-CL commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHandlers/ExecuteSearchHandler.cs
> +
Unnecessary whitespace change

2021-06-29 13:57 UTC, Ethan-CL commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHandlers/ExecuteSearchHandler.cs
> +
Unnecessary whitespace change

2021-06-29 14:56 UTC, cl-sambendell requested changes

2021-06-29 14:56 UTC, cl-sambendell commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +					if (EngineIncludePath.Equals(string.Empty))
In C# it looks like you're able to call instead:
```suggestion
					if (string.IsNullOrEmpty(EngineIncludePath))
```

2021-06-29 14:56 UTC, cl-sambendell commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +				if (ProjectsList[i].Name.Equals("UE4"))
What are we searching for here? UE4.sln/UE4.proj?

2021-06-29 14:56 UTC, cl-sambendell commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +			MessageBox.Show("BlueprintSearchVS could not find an unreal project in this solution.", "BlueprintSearchVS Warning");
There's a couple things in here that can be cleaned up - though I'll need some clarification on the requirements of what the code is trying to do:

- We're printing a message that a project can't be found on each iteration and then again at the end, only one of these will be needed
- I'm not a fan of having UECommandLineFilePath set to a value, then checking if the value is correct and early returning, then if not setting it back to empty. It's much cleaner and less error prone to have it always be empty and only if our checks come back correct do we set the value of UECommandLineFilePath, skipping any early returns
- UECommandLineFilePath and UProjectFilePath look like they're both linked and both are only useful is both are set, therefore they should be tied together and set at the same time

2021-06-29 14:56 UTC, cl-sambendell commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +				}
This snippet of code is heavily duplicated 3 times in this function:
Just to clarify is all we're doing searching for the Engine directory and then if we find the directory, going to Engine\\Binaries\\Win64\\UE4Editor-Cmd.exe?
If so I have some ideas

2021-06-29 14:56 UTC, cl-sambendell commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHandlers/ExecuteSearchHandler.cs
> +			//PathFinderHelper.FindPaths();
Remove commented code

2021-06-29 14:56 UTC, cl-sambendell commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHandlers/ExecuteSearchHandler.cs
> +
Removed added whitespace

2021-06-29 14:56 UTC, cl-sambendell commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +		public static string UProjectFilePath { get; set; }
I would bet this probably wants a private set; instead

2021-06-29 14:56 UTC, cl-sambendell commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +		public static string UECommandLineFilePath { get; set; }
Same here, probably wants a private set;

2021-06-29 15:07 UTC, cl-sambendell commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +			string SourceDirectoryPath;
I'm not entirely sure this will work for projects that aren't stored within the engine root folder - do we want to support this use case?

2021-06-29 15:55 UTC, cl-sambendell commented on Source/BlueprintSearchVSExtension/Source/BlueprintSearchVSPackage.cs
> +			SolutionLoaderManager.AdviseSolutionEvents(this, out SolutionEvents);
Do you need to keep a copy to this SolutionLoaderManager? It's not referenced in any other function, so you could simplify this for now to:
```suggestion
		((IVsSolution)GetService(typeof(SVsSolution))).AdviseSolutionEvents(this, out SolutionEvents);
```

2021-06-29 15:56 UTC, cl-sambendell commented on Source/BlueprintSearchVSExtension/Source/BlueprintSearchVSPackage.cs
> +			SolutionLoaderManager = GetService(typeof(SVsSolution)) as IVsSolution;
Since this is called from the async InitializeAsync, should this function not also be async and use GetServiceAsync like the InitDTEAsyns?

2021-06-30 06:22 UTC, Josef-Rare commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +			string SourceDirectoryPath;
Yes that will want supporting as it's a normal workflow. While it isn't a workflow any project we work on currently uses, I think it would be best to make sure we do support projects elsewhere on disk from the start.

Davide - it's possible to make a new UE project anywhere on your PC and associate it with an engine version in a completely different place (if you weren't aware of that already :) ).

2021-06-30 07:09 UTC, Ori-CL submitted a review, later dismissed
A couple of comments to add, Sam covered the sections of code which need looking into in more depth.

2021-06-30 07:09 UTC, Ori-CL commented on Source/BlueprintSearchVSExtension/Source/BlueprintSearchVSPackage.cs
> +		private uint SolutionEvents = uint.MaxValue;
Add a space between these variables and possibly leave a comment about what they are used for?

2021-06-30 07:09 UTC, Ori-CL commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +				if (ProjectsList[i].Name.Equals("UE4"))
In this case it would be UE4.proj, as he's verifying that this solution contains a UE4 project (otherwise we should not support the active solution with this extension's functionality).

2021-06-30 08:28 UTC, Josef-Rare commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +			for (int i = 0; i < ProjectsList.Count; ++i)
Should this be a foreach rather than an index based loop?

2021-06-30 08:45 UTC, Davide-CL commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +			string SourceDirectoryPath;
That was something I was actually afraid of, do you think is better to create a new task for it or it's something that needs to be added with this PR?

2021-06-30 09:09 UTC, Josef-Rare commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +			string SourceDirectoryPath;
New task I think. To keep your change from becoming too huge!

2021-06-30 10:10 UTC, willhinds commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +			string SourceDirectoryPath;
Might be worth for now just adding a text box to paste in the .exe and .uproject file paths in if we can't find them on disk?
I think this is a new task not this current one, but a high priority.
Maybe a more complete solution down the line would involve the Search Everything integration, if there's not a way of getting the associated engine version from the .uproject file?

2021-06-30 10:44 UTC, Josef-Rare commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +			string SourceDirectoryPath;
There is 
![image](https://user-images.githubusercontent.com/27948963/123947560-6e141b80-d998-11eb-9e94-9907cafe87db.png)
it's blank when they're in the same folder though (as far as I remember that's how it works)

2021-06-30 11:01 UTC, willhinds commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +			string SourceDirectoryPath;
Ah nice, this is JSON format too so it should be fine to grab this out of the .uproject file. It can be done in the next PR though

2021-06-30 14:47 UTC, cl-sambendell commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +				if (ProjectsList[i].Name.Equals("UE4"))
Thanks for clarifying!

2021-06-30 14:59 UTC, cl-sambendell commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +			for (int i = 0; i < ProjectsList.Count; ++i)
For reference if you've unfamiliar with C# foreach statements :)
Var name has to be some permutation of Proj/project (but not 'Project', this is why the unreal coding standard has prefix's on class names)
```suggestion
			foreach (Project project in ProjectsList)
```

2021-06-30 15:01 UTC, cl-sambendell approved these changes
All my changes were addressed, one outstanding comment left from Josef

2021-07-01 09:48 UTC, merged