added .uhtmanifest parsing to obtain unreal root folder path
CoconutLizard/BlueprintSearchVSExtension pull request #6
Opened 2021-07-13 11:05 UTC by Davide-CL

2021-07-14 08:48 UTC, Ori-CL requested changes
Left a note about a potential spelling mistake, otherwise looks good.

2021-07-14 08:48 UTC, Ori-CL commented on Source/BlueprintSearchVSExtension/Source/BlueprintSearchVSPackage.cs
> +
Can you remove this empty line.

2021-07-14 08:48 UTC, Ori-CL commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/DeserializeHelper.cs
> +	public class UthManifestJsonObject
Should this be Uht rather than Uth?

2021-07-14 09:19 UTC, Josef-Rare commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +					MessageBox.Show("BlueprintSearchVS could not find Unreal's command line executable.", "BlueprintSearchVS Warning");
```suggestion
					MessageBox.Show("BlueprintSearchVS could not find Unreal's command line executable.\nCheck that you have an up to date Development Editor build.", "BlueprintSearchVS Warning");
```

Providing this makes sense, and newlines work in this context!

2021-07-14 09:21 UTC, Josef-Rare commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +			string UhtManifestPath = Path.Combine(Path.GetFullPath(Path.Combine(DTEService.Solution.FullName, "..")), "Intermediate\\Build\\Win64\\VehicleGameEditor\\Development\\VehicleGameEditor.uhtmanifest
Do you have a plan / ideas for how to deal with finding the project name?

2021-07-14 10:16 UTC, Ori-CL approved these changes

2021-07-14 11:06 UTC, Davide-CL commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +			string UhtManifestPath = Path.Combine(Path.GetFullPath(Path.Combine(DTEService.Solution.FullName, "..")), "Intermediate\\Build\\Win64\\VehicleGameEditor\\Development\\VehicleGameEditor.uhtmanifest
Sorry Josef, I don't think I've understood your question. You mean the name of the project where we want to do the blueprint search?

2021-07-14 14:37 UTC, cl-sambendell commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +			string UhtManifestPath = Path.Combine(Path.GetFullPath(Path.Combine(DTEService.Solution.FullName, "..")), "Intermediate\\Build\\Win64\\VehicleGameEditor\\Development\\VehicleGameEditor.uhtmanifest
Since Josef has likely finished for the day, Yes the name of the project. These binaries are named after the project: `$ProjectName$Editor`, so for the `VehicleGame` project, they end up as `VehicleGameEditor`.
Where as for another project, like `ShooterGame`, these binaries would end up as `ShooterGameEditor` and so it would be unable to find these paths/files.

2021-07-14 15:12 UTC, Davide-CL commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +			string UhtManifestPath = Path.Combine(Path.GetFullPath(Path.Combine(DTEService.Solution.FullName, "..")), "Intermediate\\Build\\Win64\\VehicleGameEditor\\Development\\VehicleGameEditor.uhtmanifest
We are doing something similar with the .uproject file, we can access the current solution name from the DTE, from there is just a matter of replacing a wildcard with the name. Something like this:
![image](https://user-images.githubusercontent.com/84315156/125646873-88ee78eb-5730-426b-b334-f30819505366.png)

2021-07-16 10:17 UTC, cl-sambendell commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +			string UhtManifestPath = Path.Combine(Path.GetFullPath(Path.Combine(DTEService.Solution.FullName, "..")), "Intermediate\\Build\\Win64\\VehicleGameEditor\\Development\\VehicleGameEditor.uhtmanifest
Looks like it should be good enough to do the trick

2021-07-16 10:24 UTC, cl-sambendell approved these changes

2021-07-16 10:26 UTC, merged