Feature/blueprint search vs extension sub tasks/add context to search results displayed
CoconutLizard/BlueprintSearchVSExtension pull request #7
Opened 2021-07-30 15:09 UTC by Davide-CL

2021-08-02 08:05 UTC, Josef-Rare commented on Source/FindInBlueprintExternal/Classes/FImaginaryFiBDataAccessor.h
> +class FImaginaryFiBDataAccessor final : protected FImaginaryFiBData
You need to include the header for FImaginaryFiBData

Also is there any reason for inheriting protected? It's unusual to see it.

2021-08-02 08:10 UTC, Josef-Rare commented on Source/FindInBlueprintExternal/Private/FImaginaryFiBDataAccessor.cpp
> +	return LOCTEXT("FiBSerializationError", "There was an error in serialization!");
We should have a chat about this. My questions are going to be: who (programmer or user) could cause this path to be hit? How can they make that happen? Ultimately we want to think about if this is the best way to handle the error case and why.

2021-08-02 08:12 UTC, Josef-Rare commented on Source/FindInBlueprintExternal/Private/FiBCommandlet.cpp
> +	TArray<FAssetData> data;
```suggestion
	TArray<FAssetData> Data;
```

2021-08-02 08:12 UTC, Josef-Rare commented on Source/FindInBlueprintExternal/Private/FiBCommandlet.cpp
> +	AssetRegistryModule.Get().GetAssetsByClass(TEXT("Blueprint"), data);
```suggestion
	AssetRegistryModule.Get().GetAssetsByClass(TEXT("Blueprint"), Data);
```

2021-08-02 08:14 UTC, Josef-Rare commented on Source/FindInBlueprintExternal/Private/FiBResultsToJsonWriter.cpp
> +		for (uint8 i = 0; i < SearchResults.Num(); i++)
Give 'i' a more meaningful name please

2021-08-02 08:36 UTC, Josef-Rare commented on Source/FindInBlueprintExternal/Classes/FImaginaryFiBDataAccessor.h
> +	FString GetInfo(const FText& Category, const FText& DisplayText);
Given this class has no members to manipulate (and presumably shouldn't be modifying anythign from the parent), all these functions can likely be const.

2021-08-02 08:36 UTC, Josef-Rare commented on Source/FindInBlueprintExternal/Classes/FImaginaryFiBDataAccessor.h
> +	FString GetValue(const FText& text);
```suggestion
	FString GetValue(const FText& Text);
```

2021-08-02 08:38 UTC, Josef-Rare commented on Source/FindInBlueprintExternal/Private/FImaginaryFiBDataAccessor.cpp
> +FText FindInBlueprintsHelpers::AsFText(int32 InValue, const TMap<int32, FText>& InLookupTable)
Is this ftn body in the appropriate file?

2021-08-02 08:47 UTC, Davide-CL commented on Source/FindInBlueprintExternal/Private/FImaginaryFiBDataAccessor.cpp
> +FText FindInBlueprintsHelpers::AsFText(int32 InValue, const TMap<int32, FText>& InLookupTable)
Technically no. This is one of the reason of why I was thinking of rewriting the search code inside the commandlet. This function and GetDisplayText are both part of a classes that aren't exposed to external modules, so I had to copy and paste their definition inside FImaginaryFiBDataAccessor.cpp. I'm sure it's a very ugly thing to do but, this whole task can't be done without these two functions.

2021-08-04 06:32 UTC, Josef-Rare commented on Source/FindInBlueprintExternal/Private/FImaginaryFiBDataAccessor.cpp
> +	FSearchableValueInfoHelper(const FSearchableValueInfo& InValueInfo): FSearchableValueInfo(InValueInfo){}
Put the initialiser list and (empty) body on their own lines please.

2021-08-04 06:34 UTC, Josef-Rare commented on Source/FindInBlueprintExternal/Private/FImaginaryFiBDataAccessor.cpp
> +	FText GetDisplayText(const TMap<int32, FText>& InLookupTable) const;
As you're defining the whole class in the cpp then you don't need the declaration and definition to be separate so move line 17-30 here instead.

2021-08-04 06:42 UTC, Josef-Rare commented on Source/FindInBlueprintExternal/Private/FImaginaryFiBDataAccessor.cpp
> +			const FSearchableValueInfoHelper ValueHelper(Child.Value);
So I think here I'd pass the *LookupTablePtr param into the constructor rather than to the function call. For our use case this makes more sense, and means line 82 will look a bit neater.

2021-08-04 06:43 UTC, Josef-Rare commented on Source/FindInBlueprintExternal/Private/FImaginaryFiBDataAccessor.cpp
> +			const FString CommentMetadata = FString::Printf(TEXT("%s: %s"), *Child.Key.Text.ToString(), *ValueHelper.GetDisplayText(*LookupTablePtr).ToString());
I'd be tempted to write a function

```
GetDisplayString()
{
   return GetDisplayText().ToString();
}

2021-08-04 06:44 UTC, Josef-Rare commented on Source/FindInBlueprintExternal/Private/FImaginaryFiBDataAccessor.cpp
> +			const FString CommentMetadata = FString::Printf(TEXT("%s: %s"), *Child.Key.Text.ToString(), *ValueHelper.GetDisplayText(*LookupTablePtr).ToString());
Just to clean up these calls a little bit

2021-08-04 06:46 UTC, Josef-Rare requested changes
The logic and general structure all look good! I've just made a couple of mostly stylistic comments.

2021-08-05 08:13 UTC, Josef-Rare approved these changes

2021-08-05 08:33 UTC, merged