Feature/blueprint search vs extension sub tasks/create release vsix file
CoconutLizard/BlueprintSearchVSExtension pull request #8
Opened 2021-08-13 13:34 UTC by Davide-CL

2021-08-16 13:17 UTC, Josef-Rare commented on README.md
> +4. Open BlueprintSearch.vsix
```suggestion
4. Double click BlueprintSearch.vsix
```

Is this correct?

2021-08-16 13:19 UTC, Josef-Rare commented on README.md
> +1. Clone the repository inside your Unreal Engine plugins folder using your favourite Git client or by clicking the download ZIP button inside the Green Code submenu.
```suggestion
1. Clone the repository inside your Unreal Engine plugins (<project path>/Engine/Plugins) folder using your favourite Git client or by clicking the download ZIP button inside the Green Code submenu.
```

2021-08-16 13:21 UTC, Josef-Rare commented on README.md
> +NOTE: If BlueprintSearchVS fails find one of the file needed to execute a search. Is possible, after fixing the error, to execute another search using the button inside the BlueprintSearchVS submenu.
I'm not completely sure what this means. Is it something the extension itself can provide instructions for if the problem happens (if it's not avoidable somehow)?

I mean the error box would say. Do X, Y, Z and then try again.

2021-08-16 13:21 UTC, Josef-Rare commented on README.md
> +1. Open an Unreal Engine 4 project built against a version of the engine with the plugin in.
```suggestion
1. Open an Unreal Engine 4 project built against a version of the engine with the BlueprintSearch plugin installed.
```

2021-08-16 16:02 UTC, Davide-CL commented on README.md
> +NOTE: If BlueprintSearchVS fails find one of the file needed to execute a search. Is possible, after fixing the error, to execute another search using the button inside the BlueprintSearchVS submenu.
Currently in these message boxes I'm only printing Error + How to solve it, not what to do afterwards. These error can be caused by users, i.e. in the case they forgot to build either engine or game project. Currently I'm searching for paths only when the extension is first initialized so if one of these errors occurs the user would have to restart visual studio, to solve this problem I added a button to search for Paths again. Not sure If I'm being clear if not I can try to explain myself better during the Catch-up tomorrow.

2021-08-18 09:49 UTC, Ori-CL requested changes

2021-08-18 09:49 UTC, Ori-CL commented on README.md
> +4. Open BlueprintSearch.vsix
@Josef-CL  - Yes this is correct, any method of initializing the archive to run its installer will work (right clicking and selecting "open" will work too.

Furthermore, we could also add a step to select the relevant products for installing the extension (example installer window below). 
![VSIX_INSTALLER](https://user-images.githubusercontent.com/63600713/129875994-e3fa42f4-38d0-4a05-aded-37811e70959d.png)

2021-08-18 09:49 UTC, Ori-CL commented on README.md
> +NOTE: If BlueprintSearchVS fails find one of the file needed to execute a search. Is possible, after fixing the error, to execute another search using the button inside the BlueprintSearchVS submenu.
What you have commented makes sense @Davide-CL, I think it would be good to implement this note within the message box itself (as Josef stated), rather than in this document (or possibly include it in both), the note also needs re-articulating.

2021-08-18 13:41 UTC, Josef-Rare commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +					MessageBox.Show("BlueprintSearchVS will not work as it could not find CommandletScript.", "BlueprintSearchVS Warning");
Is it possible for the user to cause this case to happen? It looks like this is our extension's script? In that case it is our fault if it is missing and we should be expecting to have to reinstall I'd guess?

2021-08-19 06:52 UTC, Ori-CL requested changes
Very good work Davide, I left a few small comments but nothing major. Contact me on teams when you see this.

2021-08-19 06:52 UTC, Ori-CL commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +					MessageBox.Show("BlueprintSearchVS will not work as it could not find CommandletScript.", "BlueprintSearchVS Warning");
I agree with Josef here, I think it's worth altering the message by adding some information with regards to solving this problem, should they re-download the repository, or re-run a script?

2021-08-19 06:52 UTC, Ori-CL commented on Source/BlueprintSearchVSExtension/Config/source.extension.vsixmanifest
> +        <Identity Id="BlueprintSearch.c46293e0-fd4e-4e8b-a903-d90753e23089" Version="0.9.5" Language="en-US" Publisher="Coconut Lizard" />
Is this the 1.0.0 release or will that be a different one?

2021-08-19 06:52 UTC, Ori-CL commented on Source/BlueprintSearchVSExtension/Source/BlueprintSearchVSPackage.vsct
> +		<KeyBinding guid="guidBlueprintSearchPackageCmdSet" id="cmdidBlueprintSearchWindowCommand" editor="guidVSStd97" key1="0x47" mod1="Alt Shift Control" /> <!--ALT + CTRL + SHIFT + G-->
The comment here says "Alt + Ctrl + Shift + G", is this correct or is the correct one "Alt + Shift + Ctrl + G"?

2021-08-19 06:52 UTC, Ori-CL commented on README.md
> +4. Click the search button or press Enter.
Also mention the keybinding shortcut here

2021-08-19 08:35 UTC, Davide-CL commented on Source/BlueprintSearchVSExtension/Source/Commands/CommandHelpers/PathFinderHelper.cs
> +					MessageBox.Show("BlueprintSearchVS will not work as it could not find CommandletScript.", "BlueprintSearchVS Warning");
I don't think this error can be caused by a user, not involuntarily at least. This path should always exist inside the install folder. I might also remove it, to be fair. I've left it just because I don't know if it might be caused by some other circumstances.

2021-08-19 10:02 UTC, Ori-CL approved these changes
LGTM!

2021-08-19 15:27 UTC, merged